/**
 * Shared API envelope and header types.
 *
 * These types are the single source of truth for the header-aware API client
 * (`useApiClient`) and all domain composables. Every response returned from
 * `$fetch.raw` is normalized into `ApiResponse<T>` before any data is rendered.
 *
 * Requirements: 3.5, 4.2, 7.1
 * Design: Data Models (New schemas); Composables and API Client Design
 */

/**
 * Typed view of the HTTP response headers the Nuxt proxy forwards to the browser.
 *
 * `server/utils/backendApi.ts` forwards: ETag, Location, Vary, X-Correlation-ID,
 * Cache-Control, Accept-Patch, Allow.  All fields are optional because any given
 * endpoint may not include every header.
 */
export interface ApiHeaders {
  /** ETag version identifier for the resource (e.g. `"3"`). */
  etag?: string
  /** URI of the newly created resource; present on 201 Create responses. */
  location?: string
  /** Vary header value listing request headers that affect the response. */
  vary?: string
  /** Cache-Control directive (typically `no-store` for payment resources). */
  cacheControl?: string
  /** X-Correlation-ID tracing value generated by the backend per request. */
  correlationId?: string
  /** Allow header listing permitted HTTP methods (OPTIONS / discovery). */
  allow?: string
  /** Accept-Patch media type accepted on PATCH endpoints. */
  acceptPatch?: string
  /** Retry-After seconds value; present on 429 / 503 responses. */
  retryAfter?: string
  /** WWW-Authenticate challenge; present on 401 responses. */
  wwwAuthenticate?: string
  /** Idempotency-Replayed: true when POST returned a cached replay. */
  idempotencyReplayed?: string
  /** Last-Modified date of the resource (Phase 2). */
  lastModified?: string
  labSignature?: string
  labEventId?: string
}

/**
 * Mirrors the `application/problem+json` error body (RFC 7807 / RFC 9457).
 *
 * All standard members are optional; the index signature allows backend
 * extension members to pass through without loss (aligned with the Zod schema's
 * `.passthrough()` in `problem-details.schema.ts`).
 */
export type ProblemDetails = {
  /** URI identifying the problem type. May be `about:blank` for generic errors. */
  type?: string
  /** Short human-readable summary that does not change between occurrences. */
  title?: string
  /** HTTP status code mirroring the response status. */
  status?: number
  /** Human-readable explanation specific to this occurrence. */
  detail?: string
  /** URI of the specific resource or request that triggered the error. */
  instance?: string
  /** X-Correlation-ID from backend for tracing. */
  correlationId?: string
  /** Machine-readable error code. */
  error?: string
  /** Header name that must be supplied (428 Precondition Required). */
  requiredHeader?: string
  /** Validation field errors (400). */
  details?: Array<{ field: string; message: string }>
  /** Whether the operation can be retried (Phase 2). */
  retryable?: boolean
  /** Seconds to wait before retry (Phase 2). */
  retryAfterSeconds?: number
  /** Allow backend extension members to pass through. */
  [key: string]: unknown
}

/**
 * Normalized envelope returned by `useApiClient` for every backend response.
 *
 * - `data` holds the validated (Zod-parsed) response payload, or `null` on
 *   error or validation failure.
 * - `status` is the HTTP status code.
 * - `headers` is a typed view of the forwarded response headers.
 * - `problem` holds the parsed `application/problem+json` body, or `null` when
 *   the response is not a problem response.
 * - `raw` is the unmodified response body text, preserved for `RawJsonViewer`
 *   (Req 4.3, 8.6) before any parsing occurs.
 */
export interface ApiResponse<T> {
  data: T | null
  status: number
  headers: ApiHeaders
  problem: ProblemDetails | null
  raw: string
}
