<template>
  <UCard>
    <template #header>
      <h3 class="text-base font-semibold">Create Payment Order</h3>
    </template>

    <div class="space-y-6">
      <UAlert
        v-if="!canCreatePaymentOrder"
        color="warning"
        variant="subtle"
        icon="i-lucide-shield-alert"
        description="You do not have permission to create payment orders."
        role="alert"
      />

      <!-- Idempotency Key Input -->
      <IdempotencyKeyInput v-model="idempotencyKey" />

      <!-- Payment Order Form -->
      <UForm
        :schema="createPaymentOrderSchema"
        :state="formState"
        data-testid="create-payment-order-form"
        class="space-y-4"
        @submit="onSubmit"
      >
        <UFormField label="Amount (minor units)" name="amountMinor">
          <UInput v-model.number="formState.amountMinor" type="number" placeholder="12500" />
        </UFormField>

        <UFormField label="Currency" name="currency">
          <USelect v-model="formState.currency" :items="currencies" placeholder="Select currency" />
        </UFormField>

        <UFormField label="Client Order Reference" name="clientOrderReference">
          <UInput v-model="formState.clientOrderReference" placeholder="PAY-001" />
        </UFormField>

        <!-- Backend error / problem response -->
        <ErrorState
          v-if="errorProblem || errorMessage"
          :problem="errorProblem ?? undefined"
          :message="errorMessage ?? undefined"
        />

        <UButton
          type="submit"
          :loading="submitting"
          :disabled="!canCreatePaymentOrder"
          label="Create Payment Order"
          data-testid="action-create-payment-order"
          :aria-label="canCreatePaymentOrder ? 'Create payment order' : 'Create payment order unavailable: missing payment create authority'"
        />
      </UForm>
    </div>
  </UCard>
</template>

<script setup lang="ts">
/**
 * Create Payment Order Form (EXTENDED for task 10.2).
 *
 * Changes vs original:
 * - Delegates transport to `usePaymentOrdersApi().createOrder` (header-aware).
 * - Integrates `IdempotencyKeyInput` (generated on mount, user-editable).
 * - Idempotency-Key reuse rule:
 *     - On failure, the key is RETAINED so a retry with unchanged values reuses it.
 *     - When the user changes any form field after a failure, a new key is generated.
 * - Retains form values on failure (does NOT reset the form).
 * - Emits `debugRequest` / `debugResponse` so the parent page can wire `ApiDebugPanel`.
 * - Adds `data-testid="create-payment-order-form"` on the <form> element.
 * - Validation messages come from the existing `createPaymentOrderSchema`.
 *
 * Requirements: 3.2, 3.3, 3.4, 10.1, 10.2, 10.3, 12.3
 */
import { createPaymentOrderSchema } from '~/schemas/payment-order.schema'
import type { ProblemDetails } from '~/types/api'

const props = defineProps<{
  merchantId: string
}>()

const emit = defineEmits<{
  (e: 'created', paymentOrderId: string): void
  (e: 'debugRequest', info: { method: string; path: string; headers: Record<string, string> }): void
  (e: 'debugResponse', info: { status: number; headers: Record<string, string>; body: string }): void
}>()

const { createOrder } = usePaymentOrdersApi()
const toast = useToast()
const { can } = useAuthorization()

const submitting = ref(false)
const errorMessage = ref<string | null>(null)
const errorProblem = ref<ProblemDetails | null>(null)

/** True if the last submit resulted in a failure and form values are unchanged. */
const failedSubmitSnapshot = ref<{ amountMinor: number | undefined; currency: string | undefined; clientOrderReference: string } | null>(null)

const currencies = ['PLN', 'EUR', 'USD']

const formState = reactive({
  amountMinor: undefined as number | undefined,
  currency: undefined as 'PLN' | 'EUR' | 'USD' | undefined,
  clientOrderReference: '',
})

const canCreatePaymentOrder = computed(() => can.value.canCreatePaymentOrder)

/**
 * The idempotency key drives the IdempotencyKeyInput component.
 * Initial value is generated by the component on mount (via its own onMounted).
 * We seed it with an empty string; IdempotencyKeyInput will emit a UUID on mount.
 */
const idempotencyKey = ref('')

/**
 * Compares current form state to the last-failed snapshot.
 * Returns true when values are identical (key should be reused).
 */
function formMatchesFailedSnapshot(): boolean {
  if (!failedSubmitSnapshot.value) return false
  const snap = failedSubmitSnapshot.value
  return (
    snap.amountMinor === formState.amountMinor &&
    snap.currency === formState.currency &&
    snap.clientOrderReference === formState.clientOrderReference
  )
}

/**
 * Watch form fields: when the user changes a value after a failure,
 * generate a new idempotency key.
 */
watch(
  () => [formState.amountMinor, formState.currency, formState.clientOrderReference],
  () => {
    if (failedSubmitSnapshot.value && !formMatchesFailedSnapshot()) {
      // Values changed since last failure → generate a new key
      idempotencyKey.value = crypto.randomUUID()
      // Clear the snapshot so we don't keep comparing against stale data
      failedSubmitSnapshot.value = null
    }
  }
)

async function onSubmit() {
  if (!canCreatePaymentOrder.value) return

  submitting.value = true
  errorMessage.value = null
  errorProblem.value = null

  const path = `/api/merchants/${props.merchantId}/payment-orders`
  const requestHeaders: Record<string, string> = {
    'Idempotency-Key': idempotencyKey.value,
    'Content-Type': 'application/json',
  }

  // Emit request debug info before sending
  emit('debugRequest', {
    method: 'POST',
    path,
    headers: requestHeaders,
  })

  try {
    const response = await createOrder(
      props.merchantId,
      {
        amountMinor: formState.amountMinor!,
        currency: formState.currency!,
        clientOrderReference: formState.clientOrderReference,
      },
      idempotencyKey.value
    )

    // Emit response debug info
    emit('debugResponse', {
      status: response.status,
      headers: {
        ...(response.headers.etag ? { 'ETag': response.headers.etag } : {}),
        ...(response.headers.location ? { 'Location': response.headers.location } : {}),
        ...(response.headers.vary ? { 'Vary': response.headers.vary } : {}),
        ...(response.headers.cacheControl ? { 'Cache-Control': response.headers.cacheControl } : {}),
        ...(response.headers.correlationId ? { 'X-Correlation-ID': response.headers.correlationId } : {}),
      },
      body: response.raw,
    })

    if (response.problem || !response.data) {
      // API returned a failure — retain form values, retain idempotency key
      errorProblem.value = response.problem
      errorMessage.value = response.problem
        ? null
        : 'Failed to create payment order. Please try again.'

      // Capture snapshot so we know to reuse key on unchanged resubmit
      failedSubmitSnapshot.value = {
        amountMinor: formState.amountMinor,
        currency: formState.currency,
        clientOrderReference: formState.clientOrderReference,
      }
      return
    }

    // Success — reset form, generate a fresh key, show toast
    formState.amountMinor = undefined
    formState.currency = undefined
    formState.clientOrderReference = ''
    idempotencyKey.value = crypto.randomUUID()
    failedSubmitSnapshot.value = null

    toast.add({
      title: `Payment order ${response.data.paymentOrderId} created successfully`,
      color: 'success',
    })

    emit('created', response.data.paymentOrderId)
  } catch {
    // Unexpected transport error
    errorMessage.value = 'An unexpected error occurred. Please try again.'

    // Retain key for reuse on unchanged resubmit
    failedSubmitSnapshot.value = {
      amountMinor: formState.amountMinor,
      currency: formState.currency,
      clientOrderReference: formState.clientOrderReference,
    }
  } finally {
    submitting.value = false
  }
}
</script>
